version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: perng-db
    ports:
      - 5432:5432
    env_file:
      - server/.env
    networks:
      - private
      - public
    tty: true

networks:
  public:
  private:
volumes:
  application:
